export const GlobalMatrixGatewayABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_addressResolver", type: "address", internalType: "address" },
      { name: "deployerContract_", type: "address", internalType: "address" },
      {
        name: "feesData_",
        type: "tuple",
        internalType: "struct FeesData",
        components: [
          { name: "feePoolChain", type: "uint32", internalType: "uint32" },
          { name: "feePoolToken", type: "address", internalType: "address" },
          { name: "maxFees", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addPlayerInMap",
    inputs: [
      { name: "player", type: "address", internalType: "address" },
      { name: "mapId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addressResolver",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IAddressResolver" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allContractsDeployed",
    inputs: [{ name: "chainSlug_", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "auctionHouse",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IAuctionHouse" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "chainContracts",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createMap",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createObject",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_chainId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createPlayer",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_userAddress", type: "address", internalType: "address" },
      { name: "_chainId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "feesData",
    inputs: [],
    outputs: [
      { name: "feePoolChain", type: "uint32", internalType: "uint32" },
      { name: "feePoolToken", type: "address", internalType: "address" },
      { name: "maxFees", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCloseProximityPlayers",
    inputs: [{ name: "mapId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256[][]", internalType: "uint256[][]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFeesData",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct FeesData",
        components: [
          { name: "feePoolChain", type: "uint32", internalType: "uint32" },
          { name: "feePoolToken", type: "address", internalType: "address" },
          { name: "maxFees", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMap",
    inputs: [{ name: "mapId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "address[]", internalType: "address[]" },
      {
        name: "",
        type: "tuple[]",
        internalType: "struct GlobalMatrixGateway.Location[]",
        components: [
          { name: "x", type: "uint256", internalType: "uint256" },
          { name: "y", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerLocation",
    inputs: [{ name: "player", type: "address", internalType: "address" }],
    outputs: [
      { name: "x", type: "uint256", internalType: "uint256" },
      { name: "y", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isReadCall",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isValidPromise",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mapCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mapToPlayers",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "personCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerChainId",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerImage",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerToMap",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sendMessage",
    inputs: [
      { name: "sender", type: "address", internalType: "address" },
      { name: "receiver", type: "address", internalType: "address" },
      { name: "content", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setChainContract",
    inputs: [
      { name: "chainId", type: "uint256", internalType: "uint256" },
      { name: "chainContract", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFees",
    inputs: [
      {
        name: "feesData_",
        type: "tuple",
        internalType: "struct FeesData",
        components: [
          { name: "feePoolChain", type: "uint32", internalType: "uint32" },
          { name: "feePoolToken", type: "address", internalType: "address" },
          { name: "maxFees", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlayerImage",
    inputs: [
      { name: "player", type: "address", internalType: "address" },
      { name: "imageURL", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePlayerLocation",
    inputs: [
      { name: "playerAddress", type: "address", internalType: "address" },
      { name: "x", type: "uint256", internalType: "uint256" },
      { name: "y", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "watcherPrecompile",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IWatcherPrecompile" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "MessageSent",
    inputs: [
      { name: "sender", type: "address", indexed: false, internalType: "address" },
      { name: "receiver", type: "address", indexed: false, internalType: "address" },
      { name: "content", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerAdded",
    inputs: [
      { name: "player", type: "address", indexed: false, internalType: "address" },
      { name: "chainId", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "FeesDataNotSet", inputs: [] },
  { type: "error", name: "InvalidPromise", inputs: [] },
] as const;
