export const MatrixDeployerABI = [
  {
    type: "constructor",
    inputs: [
      { name: "addressResolver_", type: "address", internalType: "address" },
      {
        name: "feesData_",
        type: "tuple",
        internalType: "struct FeesData",
        components: [
          { name: "feePoolChain", type: "uint32", internalType: "uint32" },
          { name: "feePoolToken", type: "address", internalType: "address" },
          { name: "maxFees", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addressResolver",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IAddressResolver" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allContractsDeployed",
    inputs: [{ name: "chainSlug", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "auctionHouse",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IAuctionHouse" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "counter",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creationCodeWithArgs",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deployContracts",
    inputs: [{ name: "chainSlug", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "feesData",
    inputs: [],
    outputs: [
      { name: "feePoolChain", type: "uint32", internalType: "uint32" },
      { name: "feePoolToken", type: "address", internalType: "address" },
      { name: "maxFees", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forwarderAddresses",
    inputs: [
      { name: "", type: "bytes32", internalType: "bytes32" },
      { name: "", type: "uint32", internalType: "uint32" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFeesData",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct FeesData",
        components: [
          { name: "feePoolChain", type: "uint32", internalType: "uint32" },
          { name: "feePoolToken", type: "address", internalType: "address" },
          { name: "maxFees", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOnChainAddress",
    inputs: [
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
      { name: "chainSlug", type: "uint32", internalType: "uint32" },
    ],
    outputs: [{ name: "onChainAddress", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSocketAddress",
    inputs: [{ name: "chainSlug", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [{ name: "chainSlug", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isReadCall",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isValidPromise",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setFees",
    inputs: [
      {
        name: "feesData_",
        type: "tuple",
        internalType: "struct FeesData",
        components: [
          { name: "feePoolChain", type: "uint32", internalType: "uint32" },
          { name: "feePoolToken", type: "address", internalType: "address" },
          { name: "maxFees", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setForwarderContract",
    inputs: [
      { name: "chainSlug", type: "uint32", internalType: "uint32" },
      { name: "forwarderContractAddr", type: "address", internalType: "address" },
      { name: "contractId", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "watcherPrecompile",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IWatcherPrecompile" }],
    stateMutability: "view",
  },
  { type: "error", name: "FeesDataNotSet", inputs: [] },
  { type: "error", name: "InvalidPromise", inputs: [] },
] as const;
